version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: app_container
    ports:
      - "4444:3000"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: api_container
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/api
    command: sh -c "npm install && npm run start"
    depends_on:
      - db
    networks:
      - default
  db:
    image: mysql:5.7
    container_name: db_container
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - /var/lib/mysql
    networks:
      - default
networks:
  default: